// Generated by https://pagedraw.io/pages/11802
import React from 'react';
import './webframe.css';


export default class Webframe extends React.Component {
  render() {
    return (
      <div className="webframe-webframe-0">
          <div className="webframe-0">
              <div className="webframe-title-0">
                  <div className="webframe-0-0-0">
                      <div className="webframe-the_shoes_shopping_store-0">
                          The Shoes Shopping Store
                      </div>
                  </div>
              </div>
              <div className="webframe-shoesel-0">
                  <div className="webframe-0-1-0">
                      <div className="webframe-shoe_selections-0">
                          Shoe Selections
                      </div>
                  </div>
              </div>
              <div className="webframe-checkout-0">
                  <div className="webframe-0-2-0">
                      <div className="webframe-cart_checkout-0">
                          Cart Checkout
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-1">
              <div className="webframe-1-0">
                  <div className="webframe-1-0-0">
                      <div className="webframe-cardbox-0">
                          <div className="webframe-1-0-0-0-0">
                              <img src="https://ucarecdn.com/1193d260-9c6a-431d-8a93-b753d95b5b0e/" className="webframe-image_2" /> 
                          </div>
                          <div className="webframe-1-0-0-0-1">
                              <div className="webframe-price-0">
                                  <div className="webframe-1-0-0-0-1-0-0">
                                      <div className="webframe-_4">$40.00</div>
                                  </div>
                              </div>
                          </div>
                          <div className="webframe-1-0-0-0-2">
                              <div className="webframe-addtocart-0">
                                  <div className="webframe-1-0-0-0-2-0-0">
                                      <div className="webframe-add_to_cart-0">Add to Cart</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-1-1">
                  <div className="webframe-1-1-0">
                      <div className="webframe-cardbox-00">
                          <div className="webframe-1-1-0-0-0">
                              <img src="https://ucarecdn.com/c1b2e6d1-5470-4bce-8461-4b05c163de80/" className="webframe-image-6" /> 
                          </div>
                          <div className="webframe-1-1-0-0-1">
                              <div className="webframe-price-00">
                                  <div className="webframe-1-1-0-0-1-0-0">
                                      <div className="webframe-_3">$30.00</div>
                                  </div>
                              </div>
                          </div>
                          <div className="webframe-1-1-0-0-2">
                              <div className="webframe-addtocart-00">
                                  <div className="webframe-1-1-0-0-2-0-0">
                                      <div className="webframe-add_to_cart-00">Add to Cart</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
